### ISSUE TITLE
Getting "TypeError [ERR_INVALID_ARG_TYPE]: The "timeout" argument must be of type number. Received an instance of Object" when using "got"

### ISSUE THREAD

**Issue by KnisterPeter** [mswjs/node-request-interceptor#86] opened 2021-01-12 11:11 UTC
When using msw on node for requests created by [got](https://www.npmjs.com/package/got) I'll get the following error.

```xxx:error TypeError [ERR_INVALID_ARG_TYPE]: The "timeout" argument must be of type number. Received an instance of Object
    at validateNumber (internal/validators.js:129:11)
    at getTimerDuration (internal/timers.js:381:3)
    at new ClientRequest (_http_client.js:170:20)
    at request (http.js:50:10)
    at Object.proxiedOriginalRequest (./node_modules/node-request-interceptor/src/interceptors/ClientRequest/index.ts:67:29)
    at ClientRequestOverride.<anonymous> (./node_modules/node-request-interceptor/src/interceptors/ClientRequest/ClientRequestOverride.ts:268:15)
    at step (./node_modules/node-request-interceptor/lib/interceptors/ClientRequest/ClientRequestOverride.js:33:23)
    at Object.next (./node_modules/node-request-interceptor/lib/interceptors/ClientRequest/ClientRequestOverride.js:14:53)
    at fulfilled (./node_modules/node-request-interceptor/lib/interceptors/ClientRequest/ClientRequestOverride.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
The initial requested created by me doesn't even contain a timeout value.
I've created a minimal repo to showcase the error: https://github.com/KnisterPeter/node-request-interceptor-with-got-issue

**Comment by kettanaito** [comment] 2021-01-12 16:33
Hey, @KnisterPeter. Thank you for reporting this and extra thanks for preparing the reproduction repo.

I can confirm the issue is reproducible: I was able to reproduce it in your repo as well as in a separate test (when a bypassed request made with got happens).

**Comment by kettanaito** [comment] 2021-01-12 16:37
For some reason when the bypassed request issued with `got` happens, the `options` provided to `ClientRequest` contain this:

https://github.com/mswjs/node-request-interceptor/blob/2f5a6458f41ce1b3e83eabc15a59778579d8155d/src/interceptors/ClientRequest/ClientRequestOverride.ts#L281-L283

```js
timeout: {},
```



That's not a valid value for the `timeout` property, so we see the respective exception being thrown.

**Comment by kettanaito** [comment] 2021-01-12 16:44
That `timeout` seems to be set by the `got` library here:

https://github.com/sindresorhus/got/blob/8b88be2c66d3c7d3619df283eb2d852164b92259/source/index.ts#L43

I assume that the options object is later used as an input to `ClientRequest`. What I yet fail to understand is why the initial `options` object in the interceptor has `timeout: undefined`, but somehow in the `this.end` function context it becomes `timeout: {}`.

**Comment by kettanaito** [comment] 2021-01-12 17:09
I've submitted an issue in the `got` repository to ask the maintainers for help. I don't have enough info as of now, but I suspect the handling of `options.timeout` is not correct on the `got`'s side.

**Comment by rssfrncs** [comment] 2021-03-08 10:16
is there a fix for this or a workaround?

**Comment by kettanaito** [comment] 2021-03-08 11:26
Hey, @rssfrncs. There's a partial fix open in #87, but as mentioned above, there seems to be an issue on `got` side (https://github.com/sindresorhus/got/issues/1579). Even if we merge the partial fix, the error won't go away. You can upvote the referenced `got` issue to show you're experiencing this, but there's no other option than to wait for them to address it, or provide us with the official guidance.

**Comment by kettanaito** [comment] 2021-03-21 14:05
We've got some help from the `got` maintainers and will ship the fix in the next release.

**Closed** 2021-03-21 14:59 UTC

**Comment by QuentinDejean** [comment] 2021-03-23 02:03
Hey @kettanaito , thanks for the update, great stuff! May I know when is the next release happening? We'd love to take advantage of this feature as soon as it's done!

**Comment by kettanaito** [comment] 2021-03-23 12:21
@QuentinDejean, hey. This has already been released under `@mswjs/interceptors`. We have renamed the package because it no longer deals with Node.js interception exclusively. Migrate from `node-request-interceptor` to the aforementioned package and you will have the fix.

**MSW users note:** if you're experiencing this issue in MSW, please await for the next release that should happen this month. Thanks.
