### ISSUE TITLE
XMLHttpRequest.DONE is undefined after setupServer

### ISSUE THREAD

**Issue by cainlevy** [mswjs/node-request-interceptor#78] opened 2020-12-17 05:26 UTC
In my Jest test:

```js
import {setupServer} from 'msw/node';

console.log(XMLHttpRequest.DONE);
// logs: 4

setupServer();

console.log(XMLHttpRequest.DONE);
// logs: undefined
```

I am using:

- node-request-interceptor@0.5.9
- msw@0.24.2
- jest@26.6.3
- jsdom@16.4.0

**Comment by marcosvega91** [comment] 2020-12-17 08:21
Hi @cainlevy thanks for raising this :).

Yes you're right we should define those properties as static in the override class. Do you wanna work on a fix ? Thanks 😊

**Comment by kettanaito** [comment] 2020-12-17 08:35
I believe the issue is that the request states are not marked as `static`, as Marco has rightfully mentioned:

https://github.com/mswjs/node-request-interceptor/blob/62f2a406ea24fdc35e660aa6f888c0ff99d979d5/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts#L40-L45

Shouldn't be a challenging task. Looking forward to the pull request!

**Closed** 2020-12-20 10:19 UTC
Labels: bug, good first issue, scope:xhr
