### ISSUE TITLE
Crash when response is empty

### ISSUE THREAD

**Issue by joccd** [mswjs/node-request-interceptor#71] opened 2020-11-28 00:17 UTC
Hi,

Thanks for your work !

Since last version, when the response is empty my tests with msw crashes :
![image](https://user-images.githubusercontent.com/22839734/100489769-aa3b8100-3116-11eb-9853-521b600126bb.png)
![image](https://user-images.githubusercontent.com/22839734/100489779-be7f7e00-3116-11eb-9b87-226f8a3d37a4.png)
![image](https://user-images.githubusercontent.com/22839734/100489812-f25aa380-3116-11eb-9249-ec2b42544961.png)

Is the response now mandatory ?

Regards,
Joccd

**Comment by kettanaito** [comment] 2020-11-28 10:33
Hey, @joccd. Thank you for reporting this.

No, the response must not be mandatory, this is an issue. Perhaps a regression of #70. I will take a look.

**Comment by kettanaito** [comment] 2020-11-28 10:40
Could you please run the same command you do to get the reproduction above with the `DEBUG=*` flag?

```bash
$ DEBUG=* your-command
```

I'd like to know what it assigns `this.response` to. Thanks.

**Comment by kettanaito** [comment] 2020-11-28 10:42
As after #70 the XHR response can also be of type `Blob` and `ArrayBuffer` (as well as JSON), determining its length as `this.response.length` is not a good idea. I wonder if we can base the progress length on the stringified response body, which is a `mockedResponse.body` assigned to `this.responseText` (textual representation of an XHR response body). 

Currently, I cannot reproduce your scenario in a test, so I must be missing something.

**Comment by joccd** [comment] 2020-11-28 14:41
```
[...]
 RequestInterceptor created new RequestInterceptor { interceptors: [ [Function], [Function] ] } +0ms
  http override patching "http" module... +0ms
  http override patching "https" module... +14ms
  XHR patching "XMLHttpRequest" module... +0ms
[...]
 RequestInterceptor use [Function] +4s
  XHR GET /v1/dossiers/recents?nombre=1 open {
  method: 'GET',
  url: '/v1/dossiers/recents?nombre=1',
  async: true,
  user: undefined,
  password: undefined
} +0ms
  XHR GET /v1/dossiers/recents?nombre=1 reset +6ms
  XHR GET /v1/dossiers/recents?nombre=1 set request header Accept application/json, text/plain, */* +7ms
  XHR GET /v1/dossiers/recents?nombre=1 set request header Authorization bearer abcd +11ms
  XHR GET /v1/dossiers/recents?nombre=1 send GET /v1/dossiers/recents?nombre=1 +10ms
  XHR GET /v1/dossiers/recents?nombre=1 request headers {
  accept: 'application/json, text/plain, */*',
  authorization: 'bearer abcd'
} +1ms
  XHR GET /v1/dossiers/recents?nombre=1 awaiting mocked response... +26ms
  RequestInterceptor applying middleware... {
  url: URL {},
  method: 'GET',
  body: '',
  headers: {
    accept: 'application/json, text/plain, */*',
    authorization: 'bearer abcd'
  }
} +365ms
  XHR GET /v1/dossiers/recents?nombre=1 received mocked response {
  status: 403,
  statusText: 'Forbidden',
  headers: { 'x-powered-by': 'msw' },
  body: null
} +60ms
  XHR GET /v1/dossiers/recents?nombre=1 assigned response status 403 Forbidden +4ms
  XHR GET /v1/dossiers/recents?nombre=1 assigned response headers { 'x-powered-by': 'msw' } +7ms
  XHR GET /v1/dossiers/recents?nombre=1 response type text +12ms
  XHR GET /v1/dossiers/recents?nombre=1 assigned response body null +3ms
  RequestInterceptor restore +271ms
  http override restoring patches... +4s
  XHR restoring patches... +4s
(node:22864) UnhandledPromiseRejectionWarning: TestingLibraryElementError: Caught error after test environment was torn down

Unable to find an element by: [data-testid="headerRightBlockDossierEnCours"]

<body />
(node:22864) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22864) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[my test failed]
    TypeError: Cannot read property 'length' of null

      at node_modules/node-request-interceptor/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts:280:37
```

And the content of this :

```
 XMLHttpRequestOverride {
      requestHeaders: {
        Accept: 'application/json, text/plain, */*',
        Authorization: 'bearer abcd'
      },
      responseHeaders: { 'x-powered-by': 'msw' },
      _events: [],
      UNSENT: 0,
      OPENED: 1,
      HEADERS_RECEIVED: 2,
      LOADING: 3,
      DONE: 4,
      onreadystatechange: [Function: handleLoad],
      onabort: [Function: handleAbort],
      onerror: [Function: handleError],
      onload: null,
      onloadend: null,
      onloadstart: null,
      onprogress: null,
      ontimeout: [Function: handleTimeout],
      url: '/v1/dossiers/recents?nombre=1',
      method: 'GET',
      readyState: 2,
      withCredentials: false,
      status: 403,
      statusText: 'Forbidden',
      data: '',
      response: null,
      responseType: 'text',
      responseText: '',
      responseXML: null,
      responseURL: '',
      upload: null,
      timeout: 0,
      async: true,
      user: undefined,
      password: undefined
    }
```

![image](https://user-images.githubusercontent.com/22839734/100518079-9c761200-318f-11eb-9dfe-04a3577daa62.png)
![image](https://user-images.githubusercontent.com/22839734/100518121-d7784580-318f-11eb-97d6-efd764581260.png)

I am very sorry I cannot reproduce my issue with the msw example

**Comment by kettanaito** [comment] 2020-11-29 13:55
Thank you for the debug log above, it's been a tremendous help!

I've reproduce this issue and can conclude that it's indeed a bug on the MSW side. `body: null` is not a valid mocked response body provided to `node-request-interceptor`. `body: string | undefined` is the expected correct type signature.

Nevertheless, when you don't set an explicit mocked response body (like in your usage example with MSW), the body gets provided as `null`, causing the aforementioned progress calculation exception on NRI's side. 

More technically, the `getResponseBody` function of `XMLHttpRequest` should never accept `null` as an input:

https://github.com/mswjs/node-request-interceptor/blob/454d04447aa04d493bb9e3c3235d8451ef78f02f/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts#L434-L461

As the `responseType: "text"` falls through the `default` case above, you receive `null` as the response value back, and the references to `this.response.length` error (`null.length`).

**Closed** 2020-11-29 14:05 UTC
